name: Close PR with "test" Label

on:
  pull_request:
    types:
      - labeled

jobs:
  close-pr-if-test-label:
    runs-on: ubuntu-latest
    if: contains(github.event.pull_request.labels.*.name, 'test')

    steps:
      - name: Close PR
        uses: peter-evans/close-pull-request@v2
        with:
          pull-request-number: ${{ github.event.pull_request.number }}
          comment: 'Closing this PR automatically because it has the label "test".'
