name: Auto-close PRs with "test" Label

on:
  pull_request:
    types:
      - labeled

jobs:
  close-pr:
    if: contains(github.event.pull_request.labels.*.name, 'test')
    runs-on: ubuntu-latest

    steps:
      - name: Close PR via GitHub CLI
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh pr close ${{ github.event.pull_request.number }} --repo ${{ github.repository }}
