name: Auto-close PRs with "test" Label

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'  # at 00:00 UTC

jobs:
  close-prs:
    runs-on: ubuntu-latest

    steps:
      - name: Close all open PRs with label "test"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          prs=$(gh pr list --state open --label test --json number --jq '.[].number')

          if [ -z "$prs" ]; then
            echo "✅ No open PRs with label 'test'."
            exit 0
          fi

          for pr in $prs; do
            echo "❌ Closing PR #$pr"
            gh pr close "$pr" --repo "$GITHUB_REPOSITORY"
          done
