name: Generate HTTP Server Style Index (Inline, Fork Only)

on:
  push:
    paths:
      - 'posts/**'

jobs:
  generate-index:
    runs-on: ubuntu-latest

    steps:
      - name: Check if fork
        run: |
          if [ "${{ github.event.repository.fork }}" != "true" ]; then
            echo "Not a fork. Exiting."
            exit 0
          fi

      - name: Checkout
        uses: actions/checkout@v4

      - name: Generate index.html (inline Python)
        run: |
          python -c "import os, sys; from http.server import SimpleHTTPRequestHandler; from io import BytesIO; class FakeHandler(SimpleHTTPRequestHandler): def __init__(self): self.wfile = BytesIO(); self.path = '/posts'; self.directory = os.getcwd(); def send_response(self, code): pass; def send_header(self, k, v): pass; def end_headers(self): pass; handler = FakeHandler(); handler.list_directory(os.path.join(os.getcwd(), 'posts')); open('index.html','wb').write(handler.wfile.getvalue())"

      - name: Commit index.html
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "actions@github.com"
          git add index.html
          git commit -m "Update index.html [skip ci]" || echo "No changes"
          git push
