name: Generate Directory Tree (Node, Single Command, Fork Only)

on:
  push:
    paths:
      - 'posts/**'

jobs:
  generate-index:
    runs-on: ubuntu-latest

    steps:
      - name: Check if fork
        run: |
          if [ "${{ github.event.repository.fork }}" != "true" ]; then
            echo "Not a fork. Skipping."
            exit 0
          fi

      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install directory-tree
        run: npm install directory-tree

      - name: Generate index.html (single Node.js command)
        run: |
          node -e "
          const fs = require('fs');
          const tree = require('directory-tree');
          const render = (node, prefix = '') => {
            let html = '';
            if (node.type === 'directory') {
              html += \`\${prefix}<strong>\${node.name}/</strong><br>\`;
              (node.children || []).forEach(child => { html += render(child, prefix + '&nbsp;&nbsp;&nbsp;'); });
            } else {
              html += \`\${prefix}<a href=\"\${node.path}\">\${node.name}</a><br>\`;
            }
            return html;
          };
          const data = tree('./posts');
          const html = \`<!DOCTYPE html><html><head><meta charset='utf-8'><title>Index</title><style>body{font-family:monospace;}</style></head><body>\` + render(data) + '</body></html>';
          fs.writeFileSync('index.html', html);
          "

      - name: Commit index.html
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "actions@github.com"
          git add index.html
          git commit -m "Update index.html [skip ci]" || echo "No changes"
          git push
