name: Validate Jekyll Posts

on:
  pull_request:
    paths:
      - 'posts/**'

jobs:
  jekyll-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout posts repository (this repo)
        uses: actions/checkout@v4

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2
          bundler-cache: true

      - name: Validate Front Matter in Posts
        run: |
          fail=0
          for file in posts/*.md; do
            echo "Checking $file"

            if ! awk '/^---/{c++} END{exit !(c>=2)}' "$file"; then
              echo "::error file=$file::Missing front matter block"
              fail=1
              continue
            fi

            if ! grep -q '^title:' "$file"; then
              echo "::error file=$file::Missing 'title' field"
              fail=1
            fi
            if ! grep -q '^date:' "$file"; then
              echo "::error file=$file::Missing 'date' field"
              fail=1
            fi
          done
          exit $fail

      - name: Clone zunalita.github.io source (Jekyll site)
        run: |
          git clone https://github.com/zunalita/zunalita.github.io.git site

      - name: Copy posts from PR to site/_posts
        run: |
          cp posts/* site/_posts/ || true

      - name: Add html-proofer to Gemfile
        run: |
          cd site
          echo "" >> Gemfile
          echo "gem 'html-proofer'" >> Gemfile

      - name: Install site dependencies
        run: |
          cd site
          bundle install

      - name: Build Jekyll site
        run: |
          cd site
          bundle exec jekyll build --verbose

      - name: Run HTML Proofer
        run: |
          cd site
          bundle exec htmlproofer ./_site --allow-hash-href --disable-external

      - name: Upload Generated HTML posts as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: generated-posts-html
          path: site/_site/posts/
