name: Validate Jekyll Posts and Generate Real Preview

on:
  pull_request:
    paths:
      - 'posts/**'

jobs:
  validate-and-preview:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout PR Repository (Posts Repo)
        uses: actions/checkout@v4

      - name: Clone Zunalita GitHub Pages Repo
        run: |
          git clone https://github.com/zunalita/zunalita.github.io.git site

      - name: Copy PR Posts into Site
        run: |
          mkdir -p site/_posts
          cp posts/* site/_posts/ || true

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2
          bundler-cache: true

      - name: Install Site Dependencies
        run: |
          cd site
          bundle install

      - name: Build Full Jekyll Site
        run: |
          cd site
          bundle exec jekyll build --verbose

      - name: Generate Posts Preview HTML
        run: |
          echo "<html><body><h1>Post Preview</h1><table border='1'><tr><th>Filename</th><th>Title</th><th>Date</th><th>Tags</th></tr>" > site/posts_preview.html

          for file in posts/*.md; do
            filename=$(basename "$file")

            title=$(grep '^title:' "$file" | sed 's/title:[ ]*//')
            date=$(grep '^date:' "$file" | sed 's/date:[ ]*//')
            tags=$(grep '^tags:' "$file" | sed 's/tags:[ ]*//')

            echo "<tr><td>$filename</td><td>$title</td><td>$date</td><td>$tags</td></tr>" >> site/posts_preview.html
          done

          echo "</table></body></html>" >> site/posts_preview.html

      - name: Upload Preview HTML as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: posts-preview
          path: site/posts_preview.html

      - name: Post Preview Link in PR Comment
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          PREVIEW_URL="(Download the HTML preview from the workflow artifacts above 👆)"

          gh pr comment ${{ github.event.pull_request.number }} --body "**✅ Jekyll Preview Generated:** $PREVIEW_URL"

